services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/app:cached
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: lucasrangel
      POSTGRES_PASSWORD: scrapyword
      POSTGRES_DB: scrapy_data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    

    
# AIRFLOW 3.1.5
    
  airflow-db:
    image: postgres:15
    environment:
      -  POSTGRES_USER=airflow
      -  POSTGRES_PASSWORD=airflow
      -  POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
  
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: bash -c "airflow version && airflow db migrate"
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
  
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: api-server
    depends_on:
      airflow-db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: scheduler
    depends_on:
      airflow-webserver:
        condition: service_started
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - .:/opt/airflow/project
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    
volumes:
    postgres-data:  