name: 'my_transformations'
version: '1.0.0'
config-version: 2

profile: 'my_transformations'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

models:
  my_transformations:
    materialized: table

seeds:
  my_transformations:
    +column_types:
      id: numeric
      full_title: text
      memory: text
      storage: text
      color: text
      price: numeric
      rating: numeric
      site_name: text
      scraped_at: timestamp