my_transformations:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "db"
      port: 5432
      user: "lucasrangel"
      password: "scrapyword"
      dbname: "scrapy_data"
      schema: my_dbt_schema
  target: dev