version: 2

sources:
  - name: my_source
    database: scrapy_data
    schema: public
    tables:
    - name: raw_data
      description: "Raw data scraped from the web."
      columns:
      - name: price
        description: "Price" #these column names are used to attach tests and documentation for coworkers