name: GHA Data Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  env:
    ENV_USER: ${{ secrets.USER }}
    ENV_HOST: ${{ secrets.HOST }}
    ENV_PASSWORD: ${{ secrets.PASSWORD }}
    ENV_DATABASE: ${{ secrets.DATABASE }}
    ENV_PORT: ${{ secrets.PORT }}
  test_and_lint:
    name: "Pipeline Verification (Scrapy, dbt, gx)"
    runs-on: ubuntu-latest
    environment: Production
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.USER }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up dbt profiles
        run: |
          # Create a temporary "profiles.yml" file to run dbt
          cat <<EOF > dbt_project/profiles.yml
          my_transformations:
            outputs:
              ci:
                type: postgres
                threads: 1
                host: localhost
                port: ${{ secrets.PORT }}
                user: ${{ secrets.USER }}
                password: ${{ secrets.PASSWORD }}
                dbname: ${{ secrets.DATABASE }}
                schema: my_dbt_schema
            target: ci
          EOF
      
      - name: Python linting (Check for syntax errors)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Scrapy dry run (Check if spider starts and runs)
        run: |
          cd ecommerce_scraper && scrapy list
      
      - name: dbt seed and run
        run: |
          cd dbt_project
          dbt seed --target ci --profiles-dir .
          dbt run --select stg_data --target ci --profiles-dir .

      - name: Great Expectations test
        run: |
          python3 setup_gx.py && python3 run_validation.py
  
  build-and-push:
    needs: test_and_lint # you don't wanna build a Docker image on the Cloud if the code failed the test.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::029465353569:role/gha-oidc-role-scraper
          aws-region: sa-east-1
          role-session-name: GitHubActionsSession
        
      - name: Amazon ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: "${{ steps.login-ecr.outputs.registry }}"
          ECR_REPOSITORY: ecommerce-scraper-aws-repo
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest